slack:
  slack_enabled:
    client: true
    default: false
  slack_url:
    client: true
    default: '<incoming webhook url>'
  slack_channel:
    client: true
    default: '#general'
  slack_emoji:
    client: true
    default: ':discourse:'
  slack_posts:
    client: true
    default: false
